### ISSUE TITLE
Kindly mention How to Install this Plugin in cPanel

### ISSUE THREAD

**Issue by ariyandnath** [stefanpejcic/fixPermissions-cpanel-plugin#1]
Hello
Hope doing well

Kindly if you can mention the proper steps to install this plugin in cpanel then it might get more popularity 😎 

Thank You
Have a great day.

**Comment by stefanpejcic** [comment]
Hello,
You need WHM access.

`` `
cd /usr/local/cpanel/base/frontend/jupiter/

git clone https://github.com/stefanpejcic/fixPermissions-cpanel-plugin
```


And then just open from cpanel:
https://domain.com:2083/cpsessXXXXX/frontend/jupiter/fixPermissions-cpanel-plugin/index.live.php


If you want the icon in cpanel, use th WHM > cPanel plugin generator

**Comment by ariyandnath** [comment]
I think its not working?
![image](https://github.com/user-attachments/assets/1139b13b-4b6c-4e66-a93c-1c5c5da5addd)

**Comment by stefanpejcic** [comment]
## This is unmaintained.

Try to troubleshoot it:
Does the bash script run from terminal?
If not, do chmod +x and retry
If it does, then run the commands after that line that gets displayed: https://github.com/stefanpejcic/fixPermissions-cpanel-plugin/blob/9fb65bd5d3239c41396762a1a52e61f82b959ca5/index.live.php#L28

**Comment by ariyandnath** [comment]
Thank You for it. I have fixed it as it was Jupiter theme in my server. I have updated the exec line.
